package florinl.licenta.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DailyMarketDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailyMarketDataAllPropertiesEquals(DailyMarketData expected, DailyMarketData actual) {
        assertDailyMarketDataAutoGeneratedPropertiesEquals(expected, actual);
        assertDailyMarketDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailyMarketDataAllUpdatablePropertiesEquals(DailyMarketData expected, DailyMarketData actual) {
        assertDailyMarketDataUpdatableFieldsEquals(expected, actual);
        assertDailyMarketDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailyMarketDataAutoGeneratedPropertiesEquals(DailyMarketData expected, DailyMarketData actual) {
        assertThat(actual)
            .as("Verify DailyMarketData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailyMarketDataUpdatableFieldsEquals(DailyMarketData expected, DailyMarketData actual) {
        assertThat(actual)
            .as("Verify DailyMarketData relevant properties")
            .satisfies(a -> assertThat(a.getFetchDate()).as("check fetchDate").isEqualTo(expected.getFetchDate()))
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getMetricValue()).as("check metricValue").isEqualTo(expected.getMetricValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailyMarketDataUpdatableRelationshipsEquals(DailyMarketData expected, DailyMarketData actual) {
        // empty method
    }
}
