package florinl.licenta.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSignalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSignalAllPropertiesEquals(UserSignal expected, UserSignal actual) {
        assertUserSignalAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSignalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSignalAllUpdatablePropertiesEquals(UserSignal expected, UserSignal actual) {
        assertUserSignalUpdatableFieldsEquals(expected, actual);
        assertUserSignalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSignalAutoGeneratedPropertiesEquals(UserSignal expected, UserSignal actual) {
        assertThat(actual)
            .as("Verify UserSignal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSignalUpdatableFieldsEquals(UserSignal expected, UserSignal actual) {
        assertThat(actual)
            .as("Verify UserSignal relevant properties")
            .satisfies(a -> assertThat(a.getSignalDate()).as("check signalDate").isEqualTo(expected.getSignalDate()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getSummaryMessage()).as("check summaryMessage").isEqualTo(expected.getSummaryMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSignalUpdatableRelationshipsEquals(UserSignal expected, UserSignal actual) {
        assertThat(actual)
            .as("Verify UserSignal relationships")
            .satisfies(a -> assertThat(a.getSetting()).as("check setting").isEqualTo(expected.getSetting()));
    }
}
