package florinl.licenta.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserAlertSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAlertSettingsAllPropertiesEquals(UserAlertSettings expected, UserAlertSettings actual) {
        assertUserAlertSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertUserAlertSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAlertSettingsAllUpdatablePropertiesEquals(UserAlertSettings expected, UserAlertSettings actual) {
        assertUserAlertSettingsUpdatableFieldsEquals(expected, actual);
        assertUserAlertSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAlertSettingsAutoGeneratedPropertiesEquals(UserAlertSettings expected, UserAlertSettings actual) {
        assertThat(actual)
            .as("Verify UserAlertSettings auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAlertSettingsUpdatableFieldsEquals(UserAlertSettings expected, UserAlertSettings actual) {
        assertThat(actual)
            .as("Verify UserAlertSettings relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getThreshold()).as("check threshold").isEqualTo(expected.getThreshold()))
            .satisfies(a -> assertThat(a.getTriggerIfGreater()).as("check triggerIfGreater").isEqualTo(expected.getTriggerIfGreater()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getMinDurationMinutes()).as("check minDurationMinutes").isEqualTo(expected.getMinDurationMinutes())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAlertSettingsUpdatableRelationshipsEquals(UserAlertSettings expected, UserAlertSettings actual) {
        // empty method
    }
}
